// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDetmIKBH94NXLTANOAc62aJdoE5ICywPM',
    appId: '1:608034788331:web:2fd799b320611fd0eb3fae',
    messagingSenderId: '608034788331',
    projectId: 'sansthaeinsamvidhan-e3f81',
    authDomain: 'sansthaeinsamvidhan-e3f81.firebaseapp.com',
    storageBucket: 'sansthaeinsamvidhan-e3f81.firebasestorage.app',
    measurementId: 'G-V9CDLGSC9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWE6MQYGeUyRTgcbsmpBLOFING5T0SqvE',
    appId: '1:608034788331:android:cbf1344763f07ad6eb3fae',
    messagingSenderId: '608034788331',
    projectId: 'sansthaeinsamvidhan-e3f81',
    storageBucket: 'sansthaeinsamvidhan-e3f81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzyGc5mzsfiOVS-jmdWe1maZw8xfDivc8',
    appId: '1:608034788331:ios:b4e39c2d6ee67ea1eb3fae',
    messagingSenderId: '608034788331',
    projectId: 'sansthaeinsamvidhan-e3f81',
    storageBucket: 'sansthaeinsamvidhan-e3f81.firebasestorage.app',
    iosBundleId: 'com.example.sansthaeinSamvidhan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzyGc5mzsfiOVS-jmdWe1maZw8xfDivc8',
    appId: '1:608034788331:ios:b4e39c2d6ee67ea1eb3fae',
    messagingSenderId: '608034788331',
    projectId: 'sansthaeinsamvidhan-e3f81',
    storageBucket: 'sansthaeinsamvidhan-e3f81.firebasestorage.app',
    iosBundleId: 'com.example.sansthaeinSamvidhan',
  );
}
